allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  "@babel/core@>=7.0.0 <7.29.1": 7.29.7
  "@babel/plugin-transform-modules-systemjs@>=7.12.0 <7.29.4": 7.29.4
  "@isaacs/brace-expansion@<=5.0.0": 5.0.1
  "body-parser@>=2.0.0 <2.3.0": 2.3.0
  "brace-expansion@>=2.0.0 <2.1.2": 2.1.2
  "form-data@>=4.0.0 <4.0.6": 4.0.6
  "js-yaml@>=4.0.0 <4.1.2": 4.3.0
  "mdast-util-to-hast@>=13.0.0 <13.2.1": 13.2.1
  "minimatch@>=8.0.0 <9": 8.0.7
  "minimatch@>=10.0.0 <11": 10.2.5
  "path-to-regexp@>=8.0.0 <8.4.0": 8.4.2
  "picomatch@<2.3.2": 2.3.2
  "picomatch@>=4.0.0 <4.0.4": 4.0.5
  "postcss@<8.5.10": 8.5.10
  "qs@<6.15.2": 6.15.2
  "sharp@<0.35.0": 0.35.0
  "svgo@>=3.0.0 <3.3.4": 3.3.4
  "yaml@>=2.0.0 <2.8.3": 2.8.3
